### ISSUE TITLE
SCENECEPTION

### ISSUE THREAD

**Issue by emanisgrand** [serelium/BonneMaman#11]
We need to test that we can load a scene within a scene when building out.

**Comment by emanisgrand** [comment]
@serelium or @The-Best-Adam y'all mentioned wanting to take this on. Feel free to assign yourselves 👍

**Comment by serelium** [comment]
We can load multiple scenes at once with SceneManager.LoadScene(nameOfScene, **_LoadSceneMode.Additive_**).

**Comment by emanisgrand** [comment]
@serelium  would we also be able to change levels out?
For instance if a puzzle is complete can we load in a completely different scene that changes all of the assets in the corridor?
i.e.
` if (puzzle2 == solved) 
SceneManager.LoadScene(corridorV2, LoadSceneMode.Additive)`
