### ISSUE TITLE
Shader:: Highlights interactable objects

### ISSUE THREAD

**Issue by emanisgrand** [serelium/BonneMaman#18]
### Requires #14 to be done first

A shader script that highlights interactable objects.

**Comment by serelium** [comment]
@taterntots Will this do?
![image](https://user-images.githubusercontent.com/14181660/63665271-9d541300-c798-11e9-9723-30eadbe29ede.png)

**Comment by taterntots** [comment]
Works for me!

**Comment by serelium** [comment]
Shader is now available on the server: https://github.com/serelium/BonneMaman/commit/4a1363e170d4181231f5c554f5d51ccc99392f97

**Comment by emanisgrand** [comment]
![image](https://user-images.githubusercontent.com/11033188/63688850-79afbd80-c7d6-11e9-9480-196ddcd96656.png)
