### ISSUE TITLE
Create a shader that changes the color of an object (to a specified color) when it's exposed to a spotlight

### ISSUE THREAD

**Issue by serelium** [serelium/BonneMaman#32]
Example:
![image](https://user-images.githubusercontent.com/14181660/63829456-9adbef80-c937-11e9-9128-3876cf0a8fc2.png)

**Comment by emanisgrand** [comment]
@serelium that's awesome!

**Comment by emanisgrand** [comment]
Nice demo dude!
![shaderChanger](https://user-images.githubusercontent.com/11033188/63903553-e21bbc00-c9db-11e9-9301-4b61a096677c.gif)

**Comment by emanisgrand** [comment]
Pushed, tested, & verified
