### ISSUE TITLE
Rarely the Time Camera Fails to Swap Dimensions

### ISSUE THREAD

**Issue by taterntots** [serelium/BonneMaman#35]

**Comment by taterntots** [comment]
Reproduce:
1. Press 'Q' to pull down camera
2. Choose dimension with keypad 1, 2, or 3
3. Try to switch again

Again, the bug doesn't happen every time. Still unclear how to reproduce 100% of the time.

**Comment by serelium** [comment]
@taterntots @emanisgrand This seems to never occur anymore. Can you guys confirm?

**Comment by taterntots** [comment]
I haven't had it happen in days. I think we can close it and if anyone bumps into it again, we can deal with it then. Honestly, I'm not even sure how to recreate it if I tried.

**Comment by serelium** [comment]
The bug seems to not occur anymore. Closing this for now.
