### ISSUE TITLE
Need code to fully deactivate the future lens from shifting dimensions in time puzzle

### ISSUE THREAD

**Issue by taterntots** [serelium/BonneMaman#38]
Pretty straightforward. Once you first obtain the camera, the future lens needs to be completely inaccessible until you find the lens in the labyrinth. Currently there's code so you can swap to the future lens and have it not show the future through the camera, but you can still shift dimensions on mouse click. We want to remove the ability to change to the future dimension.

**Comment by serelium** [comment]
Functionality added in: https://github.com/serelium/BonneMaman/commit/fe1987ef2f2c8ee12ce233673b68ba8055e4eb9f
