### ISSUE TITLE
[MANDATORY] Action Required :: Brainstorm Scheduling 

### ISSUE THREAD

**Issue by emanisgrand** [serelium/BonneMaman#58]
We want to set aside about 2 hours (maybe more) for a brainstorming session to figure out what direction to take the project in next now that we're no longer part of a jam. This session would be similar to the initial jam session where we all meet remotely and in the same room for NYC folks.  Please use this ticket to discuss if Saturday 9/7 at 11:00AM EST, 10:00AM Central, 8AM PST works for everyone. 

If there is any conflict, please specify if it is with the *time* or the *date* so we can make appropriate accommodations. If you would rather waive your attendance for this meeting, just say so as a comment. Participation is highly encouraged as this will shape the upcoming design decisions for our game. 

For NYC folks, we're meeting at 555 W 18th St. 
As usual, I'll be there ahead of time. Just ring the bell when you're downstairs and check in with security. 🎸

**Comment by taterntots** [comment]
Works for me!

**Comment by serelium** [comment]
Works for me too

**Comment by Benjibass-artist** [comment]
Doesn't work for me...

**Comment by lizecaint** [comment]
Works for me.

**Comment by Benjibass-artist** [comment]
In case of the meeting being on saturday, here is my idea list
https://docs.google.com/document/d/122aGZwu8Z6QjQU40cO2lL9rsTnTt2xe_wvh_zGsPbhc/edit?usp=sharing

**Comment by emanisgrand** [comment]
I will provide lunch. Please let me know if you have any dietary restrictions in advance. Thank you!

**Comment by emanisgrand** [comment]
@The-Best-Adam I believe is on hiatus for a while.
@xFaraday do you think you can make it this Saturday?

**Comment by emanisgrand** [comment]
Progress will be marked in [the new design doc](https://github.com/serelium/BonneMaman/wiki/Brainstorm-Design-Doc) we have available and the session will be guided by the [post-jam brainstorm](https://docs.google.com/document/d/1KzT-fdBRg-k397D6PL6Hoc3LknXKjPQf1XUjOjxWcxw/edit#) document.
