### ISSUE TITLE
OutlinePrepass :: Invalid antiAliasing value

### ISSUE THREAD

**Issue by emanisgrand** [serelium/BonneMaman#63]
### Where?
Assets/Scripts/OutlineEffect/OutlinePrePass.cs:15

### What?
Invalid antiAliasing value (must be at least 1)

#### Error:
````
Invalid antiAliasing value (must be at least 1)
UnityEngine.RenderTexture:set_antiAliasing(Int32)
OutlinePrePass:OnEnable() (at Assets/Scripts/OutlineEffect/OutlinePrePass.cs:15)
````

#### Code:
![image](https://user-images.githubusercontent.com/11033188/64192401-95573b80-ce48-11e9-951c-2df1f9aedeac.png)

**Comment by serelium** [comment]
Fixed in: https://github.com/serelium/BonneMaman/commit/cdd9c0bbe1e48f66a6b17640f96d7c49654ae9f3
