### ISSUE TITLE
Movement disabled after dropping item while _examining.

### ISSUE THREAD

**Issue by emanisgrand** [serelium/BonneMaman#65]
### Requirements:
Interactable object with examine script on it. 
- Key

### Steps to reproduce
1. Walked up to Key > Picked up the key
2. Right-clicked to enable `_examining`
3. Press E to drop item (start the drop coroutine)

### Expected behavior
`_examining` is disabled. Standard movement is given back to the player

### Actual
- Examining is still enabled as indicated by the mouse on screen. 
- Can't move or look around.

### Additional notes:
![stuckasfuck](https://user-images.githubusercontent.com/11033188/64346132-95c61280-cfbf-11e9-9ee3-28734fab0c68.gif)
Somtimes the camera will do that weird slow turn thing that it does.

**Comment by serelium** [comment]
Fixed in: https://github.com/serelium/BonneMaman/commit/fa69dac1ad8fe0cba8787c2f1c40e39e73443af8
